from cli import *

big_heading("TEST COLORS")
line(style=Style.BLOCK, color=Color.BLACK)
line(style=Style.BLOCK, color=Color.BLUE)
line(style=Style.BLOCK, color=Color.GREEN)
line(style=Style.BLOCK, color=Color.CYAN)
line(style=Style.BLOCK, color=Color.RED)
line(style=Style.BLOCK, color=Color.MAGENTA)
line(style=Style.BLOCK, color=Color.YELLOW)
line(style=Style.BLOCK, color=Color.GREY)
line(style=Style.BLOCK, color=(Color.BLACK, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.BLUE, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.GREEN, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.CYAN, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.RED, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.MAGENTA, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.YELLOW, Color.INTENSE))
line(style=Style.BLOCK, color=(Color.GREY, Color.INTENSE))
line(style=Style.HASH, color=Color.BG_BLACK)
line(style=Style.HASH, color=Color.BG_BLUE)
line(style=Style.HASH, color=Color.BG_GREEN)
line(style=Style.HASH, color=Color.BG_CYAN)
line(style=Style.HASH, color=Color.BG_RED)
line(style=Style.HASH, color=Color.BG_MAGENTA)
line(style=Style.HASH, color=Color.BG_YELLOW)
line(style=Style.HASH, color=Color.BG_GREY)
line(style=Style.HASH, color=(Color.BG_BLACK, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_BLUE, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_GREEN, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_CYAN, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_RED, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_MAGENTA, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_YELLOW, Color.BG_INTENSE))
line(style=Style.HASH, color=(Color.BG_GREY, Color.BG_INTENSE))
enter("exit")