from cli import *

big_heading("TEST COLORS")
line(style=LineStyle.HASH, color=[Color.BLACK])
line(style=LineStyle.HASH, color=[Color.BLUE])
line(style=LineStyle.HASH, color=[Color.GREEN])
line(style=LineStyle.HASH, color=[Color.CYAN])
line(style=LineStyle.HASH, color=[Color.RED])
line(style=LineStyle.HASH, color=[Color.MAGENTA])
line(style=LineStyle.HASH, color=[Color.YELLOW])
line(style=LineStyle.HASH, color=[Color.GREY])
line(style=LineStyle.HASH, color=[Color.BLACK, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.BLUE, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.GREEN, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.CYAN, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.RED, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.MAGENTA, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.YELLOW, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.GREY, Color.INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_BLACK])
line(style=LineStyle.HASH, color=[Color.BG_BLUE])
line(style=LineStyle.HASH, color=[Color.BG_GREEN])
line(style=LineStyle.HASH, color=[Color.BG_CYAN])
line(style=LineStyle.HASH, color=[Color.BG_RED])
line(style=LineStyle.HASH, color=[Color.BG_MAGENTA])
line(style=LineStyle.HASH, color=[Color.BG_YELLOW])
line(style=LineStyle.HASH, color=[Color.BG_GREY])
line(style=LineStyle.HASH, color=[Color.BG_BLACK, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_BLUE, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_GREEN, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_CYAN, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_RED, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_MAGENTA, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_YELLOW, Color.BG_INTENSE])
line(style=LineStyle.HASH, color=[Color.BG_GREY, Color.BG_INTENSE])
enter("exit")